[package]
name = "sankshepa-protocol"
version = "0.1.0"
edition = "2024"

[dependencies]
nom.workspace = true
chrono.workspace = true
serde.workspace = true
anyhow.workspace = true
tracing.workspace = true
